import re

out = open("../shutter/ptp.py", "w")
out.write("# Constants extracted from gphoto2's ptp.h\n\n")
out.write("# This file has been automatically generated by build_ptph.py\n\n")

with open('ptp.h') as fh:
    for line in fh:
        line = line.strip()
        reg = r"^#define\s+([a-zA-Z0-9_]+)\s+(.*)"
        m = re.match(reg, line)
        if m:
            g = m.groups()
            name, value = g[0], g[1]
            value = value.replace("/*", "#")
            value = value.replace("//", "#")
            out.write("%s = %s\n" % (name, value))
